[workspace]
members = ["mc-booter", "mc-common", "mc-register", "mc-service"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/nautilus-ops/mcp-center"
rust-version = "1.89.0"